name: 'Build and test osm2pgsq'

inputs:
  test-wrapper:
    description: 'Wrapper to use around tests'
    required: false
    default: pg_virtualenv

runs:
    using: "composite"

    steps:
      - name: create build directory
        run: mkdir build
        shell: bash

      - name: configure
        run: |
          CMAKE_OPTIONS="-LA -DBUILD_TESTS=ON"
          if [ -z "${LUA_VERSION}" ]; then
            CMAKE_OPTIONS="$CMAKE_OPTIONS -DWITH_LUA=OFF"
          else
            CMAKE_OPTIONS="$CMAKE_OPTIONS -DWITH_LUAJIT=${LUAJIT_OPTION}"
          fi
          if [ -n "$CPP_VERSION" ]; then
            CMAKE_OPTIONS="$CMAKE_OPTIONS -DCMAKE_CXX_STANDARD=$CPP_VERSION"
          fi
          if [ -n "$BUILD_TYPE" ]; then
            CMAKE_OPTIONS="$CMAKE_OPTIONS -DCMAKE_BUILD_TYPE=$BUILD_TYPE"
          fi
          cmake $CMAKE_OPTIONS ..
        shell: bash
        working-directory: build
        env:
          CXXFLAGS: -pedantic -Wextra -Werror

      - name: build
        run: make -j3 all man
        shell: bash
        working-directory: build

      - name: test
        run: |
          if [ "$WRAPPER" = "pg_virtualenv" ]; then
            pg_virtualenv -v $POSTGRESQL_VERSION ctest --output-on-failure
          else
            $WRAPPER ctest --output-on-failure
          fi
        shell: bash
        working-directory: build
        env:
          WRAPPER: ${{ inputs.test-wrapper }}

